services:
  opensearch:
    image: opensearchstaging/opensearch:3.1.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "plugins.security.disabled=true"
      # We disabled the security plugin, but OS won't bootstrap if this isn't set ¯\_(ツ)_/¯
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=CjTMjH8L50k6T5I#53jpI$AkVnxpGmHm"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    # Uncomment to persist data across runs
    # volumes:
    #   - opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    expose:
      - "9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow"]
      interval: 20s
      timeout: 10s
      retries: 3
    networks:
      - opensearch-net
  dashboards:
    container_name: dashboards
    image: opensearchstaging/opensearch-dashboards:3.1.0
    ports:
      - "5601:5601"
    expose:
      - 5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
      ENV: development
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - opensearch-net

  nginx:
    image: kscarlett/nginx-log-generator:latest
    networks:
      - opensearch-net
    links:
      - fluentbit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: nginx.access
        fluentd-async: "true"
  apache:
    image: mingrammer/flog
    command: "--loop -d 1s"
    networks:
      - opensearch-net
    links:
      - fluentbit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: apache.access
        fluentd-async: "true"
  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit:/fluent-bit/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - opensearch-net

volumes:
  opensearch:

networks:
  opensearch-net:
