services:
  nginx:
    image: kscarlett/nginx-log-generator:latest
    environment:
      - RATE=1
    networks:
      - opensearch-net
    links:
      - fluentbit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: nginx.access_1
        fluentd-async: "true"
  nginx_2:
    image: kscarlett/nginx-log-generator:latest
    environment:
      - RATE=1
    networks:
      - opensearch-net
    links:
      - fluentbit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: nginx.access_2
        fluentd-async: "true"
  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit:/fluent-bit/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - opensearch-net

networks:
  opensearch-net:
